package Classes;
// Generated 22/09/2018 14:09:28 by Hibernate Tools 4.3.1

import Hibernate.HibernateUtil;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.FetchMode;
import org.hibernate.Session;
import org.hibernate.annotations.Fetch;




/**
 * Aluguel generated by hbm2java
 */
@Entity

@Table(name = "Aluguel")
public class Aluguel  implements java.io.Serializable {
     

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
     private int alu_cod;
    @Column 
    private int alu_imo_cod;
    @Column 
    private int alu_usu_cod;
    @Column
     private int alu_end_cod;
    @Column
    private int alu_inq_cod;
    @Column 
    private float alu_preco;
    @Column 
    private int alu_dia_pagamento;
    @Column 
    private boolean alu_pagamento;

    public int getAlu_cod() {
        return alu_cod;
    }

    public void setAlu_cod(int alu_cod) {
        this.alu_cod = alu_cod;
    }

    public int getAlu_imo_cod() {
        return alu_imo_cod;
    }

    public void setAlu_imo_cod(int alu_imo_cod) {
        this.alu_imo_cod = alu_imo_cod;
    }

    public int getAlu_usu_cod() {
        return alu_usu_cod;
    }

    public void setAlu_usu_cod(int alu_usu_cod) {
        this.alu_usu_cod = alu_usu_cod;
    }

   

    public int getAlu_end_cod() {
        return alu_end_cod;
    }

    public void setAlu_end_cod(int alu_end_cod) {
        this.alu_end_cod = alu_end_cod;
    }

    public int getAlu_inq_cod() {
        return alu_inq_cod;
    }

    public void setAlu_inq_cod(int alu_inq_cod) {
        this.alu_inq_cod = alu_inq_cod;
    }

    
   

    public float getAlu_preco() {
        return alu_preco;
    }

    public void setAlu_preco(float alu_preco) {
        this.alu_preco = alu_preco;
    }

    public int getAlu_dia_pagamento() {
        return alu_dia_pagamento;
    }

    public void setAlu_dia_pagamento(int alu_dia_pagamento) {
        this.alu_dia_pagamento = alu_dia_pagamento;
    }

    public boolean isAlu_pagamento() {
        return alu_pagamento;
    }

    public void setAlu_pagamento(boolean alu_pagamento) {
        this.alu_pagamento = alu_pagamento;
    }

    public Aluguel(){
        
    }

	public void cadastra(Aluguel alu){
            
           Session session = HibernateUtil.getSessionFactory().getCurrentSession();
           session.beginTransaction();
           session.save(alu);
           session.getTransaction().commit();
    }
        
    


}


