package Classes;
// Generated 22/09/2018 14:09:28 by Hibernate Tools 4.3.1


import Hibernate.HibernateUtil;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 * Endereco generated by hbm2java
 */

@Entity
@Table(name = "Endereco")
public class Endereco  implements java.io.Serializable {

    @Id
    private int end_cod;
    @Column 
    private String end_estado;
    @Column
     private String end_cep;
    @Column 
    private String end_bairro;
    @Column
    private String end_cidade;
    @Column
    private String end_rua;
    @Column
    private String end_numero;

    public Integer getEnd_cod() {
        return end_cod;
    }

    public void setEnd_cod(Integer end_cod) {
        this.end_cod = end_cod;
    }

    public String getEnd_estado() {
        return end_estado;
    }

    public String getEnd_bairro() {
        return end_bairro;
    }

    public void setEnd_bairro(String end_bairro) {
        this.end_bairro = end_bairro;
    }

    public void setEnd_estado(String end_estado) {
        this.end_estado = end_estado;
    }

    public String getEnd_cep() {
        return end_cep;
    }

    public void setEnd_cep(String end_cep) {
        this.end_cep = end_cep;
    }

    public String getEnd_cidade() {
        return end_cidade;
    }

    public void setEnd_cidade(String end_cidade) {
        this.end_cidade = end_cidade;
    }

    public String getEnd_rua() {
        return end_rua;
    }

    public void setEnd_rua(String end_rua) {
        this.end_rua = end_rua;
    }

    public String getEnd_numero() {
        return end_numero;
    }

    public void setEnd_numero(String end_numero) {
        this.end_numero = end_numero;
    }
    
     
     
    public Endereco() {
    }

	
    
    public void cadastra(Endereco end){
            
           SessionFactory sf = HibernateUtil.getSessionFactory();
            Session se = sf.openSession();
            
            
             
             
        
        
        Transaction tx = se.beginTransaction();
        
        se.save(end);
        
        tx.commit();
        
        se.flush();
        
        
        
        
        se.close();
    }



}


