package Classes;
// Generated 22/09/2018 14:09:28 by Hibernate Tools 4.3.1


import Hibernate.HibernateUtil;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.Session;

/**
 * Imovel generated by hbm2java
 */

@Entity
@Table(name = "Imovel")
public class Imovel  implements java.io.Serializable {

    @Id
     private int imo_cod;
    @Column
     private int imo_cod_end;
    @Column
    private int imo_tipo_cod;
    @Column
    private int imo_usu_cod;
    @Column
    private String imo_desc;
    @Column
    private float imo_valor;

    public int getImo_cod() {
        return imo_cod;
    }

    public void setImo_cod(int imo_cod) {
        this.imo_cod = imo_cod;
    }

    public int getImo_cod_end() {
        return imo_cod_end;
    }

    public void setImo_cod_end(int imo_cod_end) {
        this.imo_cod_end = imo_cod_end;
    }

    public int getImo_tipo_cod() {
        return imo_tipo_cod;
    }

    public void setImo_tipo_cod(int imo_tipo_cod) {
        this.imo_tipo_cod = imo_tipo_cod;
    }

    public int getImo_usu_cod() {
        return imo_usu_cod;
    }

    public void setImo_usu_cod(int imo_usu_cod) {
        this.imo_usu_cod = imo_usu_cod;
    }
   

    public String getImo_desc() {
        return imo_desc;
    }

    public void setImo_desc(String imo_desc) {
        this.imo_desc = imo_desc;
    }

    public float getImo_valor() {
        return imo_valor;
    }

    public void setImo_valor(float imo_valor) {
        this.imo_valor = imo_valor;
    }
     

    
    public Imovel() {
    }


 public void cadastra(Imovel imo){
            
           Session session = HibernateUtil.getSessionFactory().getCurrentSession();
           session.beginTransaction();
           session.save(imo);
           session.getTransaction().commit();
    }

}


