package Classes;
// Generated 22/09/2018 14:09:28 by Hibernate Tools 4.3.1


import Hibernate.HibernateUtil;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.Session;

/**
 * Inquilino generated by hbm2java
 */
@Entity

@Table(name = "Inquilino")
public class Inquilino  implements java.io.Serializable {
  
    @Id
    
     private Integer inq_cod;
    @Column 
    private String inq_nome;
    @Column
    private String inq_idade;
    @Column
    private String inq_cpf;
    @Column
    private String inq_email;

    public Integer getInq_cod() {
        return inq_cod;
    }

    public void setInq_cod(Integer inq_cod) {
        this.inq_cod = inq_cod;
    }

    public String getInq_nome() {
        return inq_nome;
    }

    public void setInq_nome(String inq_nome) {
        this.inq_nome = inq_nome;
    }

    public String getInq_idade() {
        return inq_idade;
    }

    public void setInq_idade(String inq_idade) {
        this.inq_idade = inq_idade;
    }

    public String getInq_cpf() {
        return inq_cpf;
    }

    public void setInq_cpf(String inq_cpf) {
        this.inq_cpf = inq_cpf;
    }

    public String getInq_email() {
        return inq_email;
    }

    public void setInq_email(String inq_email) {
        this.inq_email = inq_email;
    }

    

    public Inquilino() {
    }

	public void cadastra(Inquilino inq){
            
           Session session = HibernateUtil.getSessionFactory().getCurrentSession();
           session.beginTransaction();
           session.save(inq);
           session.getTransaction().commit();
    }
    
    


}


