package Classes;



import Hibernate.HibernateUtil;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.Session;

/**
 * Imovel generated by hbm2java
 */

@Entity
@Table(name = "Relatorio")
public class Relatorio implements Serializable {
   
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private int rel_cod;
    
    @Column
    private String rel_inq_cpf;
    @Column
    private int rel_usu_cod;
    
    @Column
    private String rel_inq_nome;
    
    @Column 
    private boolean rel_inq_pagamento;
    
    @Column
    private String rel_alu_preco;
    
    @Column
    private int rel_mes;
    
    @Column
    private String rel_endereco;
    
    @Column
    private int rel_ano;

    public int getRel_cod() {
        return rel_cod;
    }

    public void setRel_cod(int rel_cod) {
        this.rel_cod = rel_cod;
    }

    public String getRel_inq_cpf() {
        return rel_inq_cpf;
    }

    public void setRel_inq_cpf(String rel_inq_cpf) {
        this.rel_inq_cpf = rel_inq_cpf;
    }

    public String getRel_inq_nome() {
        return rel_inq_nome;
    }

    public void setRel_inq_nome(String rel_inq_nome) {
        this.rel_inq_nome = rel_inq_nome;
    }

    public boolean isRel_inq_pagamento() {
        return rel_inq_pagamento;
    }

    public void setRel_inq_pagamento(boolean rel_inq_pagamento) {
        this.rel_inq_pagamento = rel_inq_pagamento;
    }

    public String getRel_alu_preco() {
        return rel_alu_preco;
    }

    public void setRel_alu_preco(String rel_alu_preco) {
        this.rel_alu_preco = rel_alu_preco;
    }

    public int getRel_mes() {
        return rel_mes;
    }

    public void setRel_mes(int rel_mes) {
        this.rel_mes = rel_mes;
    }

    public String getRel_endereco() {
        return rel_endereco;
    }

    public void setRel_endereco(String rel_endereco) {
        this.rel_endereco = rel_endereco;
    }

    public int getRel_ano() {
        return rel_ano;
    }

    public void setRel_ano(int rel_ano) {
        this.rel_ano = rel_ano;
    }

    public int getRel_usu_cod() {
        return rel_usu_cod;
    }

    public void setRel_usu_cod(int rel_usu_cod) {
        this.rel_usu_cod = rel_usu_cod;
    }
    
    
    
    
    
    
    
    
}
